#!/bin/bash

# This is a thin wrapper around qtcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using qtcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_QTCOIND

# Grab the value of $REAL_QTCOINCLI which may be qtcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_QTCOINCLI}" "$@" | sed 's/\r//'
